package BasicExecutor_RejectedHandler;

import java.util.Date;
import java.util.concurrent.TimeUnit;

public class Task implements Runnable {

    private String name;
    private Date date;
    Task(String name ){
        this.name = name;
        date = new Date(); // record the task creation time
    }

    @Override
    public void run() {                // NOTE: thread name is from core processor, task name is generated by task class
        System.out.printf("%s Task %s started at %s\n", Thread.currentThread().getName(),name, date);
        try {
            long duration = (long) (Math.random()* 10);
            System.out.printf("Task %s takes %d time to finish\n", name,duration);
            TimeUnit.SECONDS.sleep(2);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        System.out.printf("Task %s is finished at %s\n", name, new Date());
    }

//    public String getName() {
//        return name;
//    }
}
